### ISSUE TITLE
Build system fails: file not found

### ISSUE THREAD

**Issue by Zoweb** [Virtual-PTU/Virtual-Pokemon-Tabletop#54]
## System Info
**Operating System:** Windows
**Version Name:** N/A
**Commit ID:** N/A
**Application:** AppVeyor

## Bug Details
**Exception Name:** File not found - Third Party Software
**Bug Severity:** Critical
**Stack Trace:**
```
xcopy "C:\projects\virtual-pokemon-tabletop\Third Party Software" "C:/projects/virtual-pokemon-tabletop/Virtual Pokemon Tabletop/Building Dir" /c /f /y
File not found - Third Party Software
0 File(s) copied
Command exited with code 4
```

## Description:
It looks like it's not creating the `Third Party Software` folder, so it can't be copied.

## Steps to Reproduce Issue:
Create a pull request, wait for build to error.

**Comment by AssaultBird2454** [comment]
The files that failed to copy have recently been renamed... This may be encountered in future PR's, but this failure can be overlooked... A PR that is still being worked on contains a fix to this issue...

Closed Issue
